"""empty message

Revision ID: b3c1e3543dba
Revises: 
Create Date: 2026-02-01 14:21:57.802427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c1e3543dba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('introduction', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('schedule',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ymd', sa.Date(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ymd')
    )
    op.create_table('spot_picture',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ),
    sa.PrimaryKeyConstraint('spot_id', 'url')
    )
    op.create_table('spot_tag',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ),
    sa.PrimaryKeyConstraint('spot_id', 'tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_tag')
    op.drop_table('spot_picture')
    op.drop_table('schedule')
    op.drop_table('user')
    op.drop_table('spot')
    # ### end Alembic commands ###
